# SELECT ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.NAME
# SELECT *
#     FROM ANIMAL_INS
#     LEFT OUTER JOIN ANIMAL_OUTS
#     ON ANIMAL_INS.ANIMAL_ID	= ANIMAL_OUTS.ANIMAL_ID	
#     WHERE ANIMAL_OUTS.ANIMAL_ID IS NULL

SELECT ANIMAL_OUTS.ANIMAL_ID, ANIMAL_OUTS.NAME
    FROM ANIMAL_OUTS
    LEFT OUTER JOIN ANIMAL_INS
    ON ANIMAL_OUTS.ANIMAL_ID = ANIMAL_INS.ANIMAL_ID	
    WHERE ANIMAL_INS.ANIMAL_ID IS NULL
