WITH RECURSIVE CTE AS (
    SELECT 0 AS N
    UNION ALL
    SELECT N+1
    FROM CTE
    WHERE N < 23
)
SELECT N HOUR, COUNT(ANIMAL_ID) COUNT
    FROM CTE LEFT JOIN ANIMAL_OUTS
    ON N = HOUR(DATETIME)
    GROUP BY N
    ORDER BY N