WITH A AS(
    SELECT CAR_ID, COUNT(CAR_ID)
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE MONTH(START_DATE) BETWEEN 8 AND 10
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID) >= 5
)

SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(CAR_ID) AS RECORDS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE MONTH(START_DATE) BETWEEN 8 AND 10
    AND CAR_ID IN (SELECT A.CAR_ID FROM A)
    GROUP BY CAR_ID, MONTH(START_DATE)
    HAVING COUNT(CAR_ID) != 0
    ORDER BY MONTH ASC, CAR_ID DESC